# Generated by Django 3.2.4 on 2021-06-23 23:01

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_install_trg'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='actor',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='actors_gin_trgm_idx', opclasses=('gin_trgm_ops',)),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='movies_gin_trgm_idx', opclasses=('gin_trgm_ops',)),
        ),
    ]
